version: '3.8'

services:
  patient-service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5002:5002"
    environment:
      - FLASK_ENV=development
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=patient_data_db
      - REDIS_URL=redis://redis:6379/0
      - CORS_ORIGINS=http://localhost:3000
      - LOG_LEVEL=DEBUG
      - AUTH_SERVICE_URL=http://auth-service:5001
    volumes:
      - ./logs:/app/logs
      - ./data:/app/data
    depends_on:
      - postgres
      - redis
    restart: unless-stopped
    networks:
      - app-network
      
  postgres:
    image: postgres:14
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=patient_data_db
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app-network
      
  redis:
    image: redis:7
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
    volumes:
      - redis-data:/data
    networks:
      - app-network
      
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@example.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    ports:
      - "5050:80"
    depends_on:
      - postgres
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    networks:
      - app-network

  # Include auth-service for integration, assuming you have it set up
  auth-service:
    build:
      context: ../auth-service
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    environment:
      - FLASK_ENV=development
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=auth_service_db
      - JWT_SECRET_KEY=development_secret_key
      - PASSWORD_SALT=development_salt
      - REDIS_URL=redis://redis:6379/0
      - CORS_ORIGINS=http://localhost:3000
    networks:
      - app-network
    depends_on:
      - postgres
      - redis

volumes:
  postgres-data:
  redis-data:
  pgadmin-data:

networks:
  app-network:
    driver: bridge